### ISSUE TITLE
Probabilities do not sum to 1

### ISSUE THREAD

**Issue by mlazzarin** [qiboteam/qibojit#47]
If I run the following circuit with qibojit on GPU:
```
import qibo
from qibo.models import Circuit
from qibo import gates
qibo.set_precision("single")

c = Circuit(31)
for i in range(31):
    c.add(gates.H(i))
output = c.add(gates.M(30, collapse=True))
for i in range(31):
    c.add(gates.H(i))
result = c()
```
I obtain the following error:
```
[Qibo 0.1.7rc1.dev0|INFO|2021-11-18 12:12:15]: Using qibojit backend on /GPU:0
Traceback (most recent call last):
  File ".../circuit.py", line 15, in <module>
    result = c()
  File ".../qibo/abstractions/circuit.py", line 712, in __call__
    return self.execute(initial_state=initial_state, nshots=nshots)
  File ".../qibo/core/circuit.py", line 306, in execute
    state = self._device_execute(initial_state)
  File ".../qibo/core/circuit.py", line 235, in _device_execute
    state = self._execute(initial_state=initial_state)
  File ".../qibo/core/circuit.py", line 221, in _execute
    state = self._eager_execute(state)
  File ".../qibo/core/circuit.py", line 188, in _eager_execute
    state = gate(state)
  File ".../qibo/core/gates.py", line 299, in __call__
    return getattr(self, self._active_call)(state)
  File ".../qibo/core/gates.py", line 288, in _state_vector_call
    return K.state_vector_collapse(self, state, self.result.binary[-1])
  File ".../qibo/core/measurements.py", line 111, in binary
    self._binary = self._convert_to_binary()
  File ".../qibo/core/measurements.py", line 167, in _convert_to_binary
    return K.mod(K.right_shift(self.decimal[:, K.newaxis], _range), 2)
  File ".../qibo/core/measurements.py", line 102, in decimal
    self._decimal = self._sample_shots()
  File ".../qibo/core/measurements.py", line 186, in _sample_shots
    result = K.cpu_fallback(K.sample_shots, self.probabilities, self.nshots)
  File ".../qibo/backends/abstract.py", line 110, in cpu_fallback
    return func(*args)
  File ".../qibo/backends/numpy.py", line 232, in sample_shots
    return self.random.choice(range(len(probs)), size=nshots, p=probs)
  File ".../cupy/random/_sample.py", line 190, in choice
    return rs.choice(a, size, replace, p)
  File ".../cupy/random/_generator.py", line 1042, in choice
    raise ValueError('probabilities do not sum to 1')
ValueError: probabilities do not sum to 1
```
Actually, ``probs`` sums to 0.25.

EDIT: Just wanted to add that, if I run the same circuit with a smaller number of qubits, it works fine.

**Comment by mlazzarin** [comment]
Additional experiments show that this issue appears only with ``qibo.set_precision("single")``.

**Comment by mlazzarin** [comment]
Given that the problem appears also with the numpy backend, I'll open a new issue in the qibo repository.
